sudo: false
language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - pip install -e .
  - pip install coverage
  - pip install coveralls

script: coverage run --source=incomepropertyevaluatorkit setup.py test

after_success:
  coveralls
